/**
 * src/z_memory.c
 * -------------------------------------------------------------------------
 * Banked memory access for Zork data using GBDK 2020.
 */

#include <gb/gb.h>
#include <stdint.h>
#include "z_memory.h"
#include "zork_data.h"  // Generated by bin2banks.py

 /**
  * Read a byte from the Zork data blob, switching ROM banks as needed.
  */
uint8_t z_read_byte(uint32_t address) {
    uint8_t save_bank = _current_bank;  // GBDK-provided
    uint8_t bank = (uint8_t)(address / ZORK_BANK_SIZE) + ZORK_DATA_BANK_START;
    uint16_t offset = (uint16_t)(address % ZORK_BANK_SIZE);

    SWITCH_ROM(bank);
    const unsigned char* bank_ptr;

    // Access the correct bank array
    switch (bank) {
    case 1: bank_ptr = zork_bank1_data; break;
    case 2: bank_ptr = zork_bank2_data; break;
    case 3: bank_ptr = zork_bank3_data; break;
    case 4: bank_ptr = zork_bank4_data; break;
    case 5: bank_ptr = zork_bank5_data; break;
    case 6: bank_ptr = zork_bank6_data; break;
    case 7: bank_ptr = zork_bank7_data; break;
    case 8: bank_ptr = zork_bank8_data; break;
    default: bank_ptr = zork_bank1_data; break;  // Fallback
    }

    uint8_t value = bank_ptr[offset];
    SWITCH_ROM(save_bank);
    return value;
}

uint16_t z_read_word(uint32_t address) {
    return ((uint16_t)z_read_byte(address) << 8) | z_read_byte(address + 1);
}

/**
 * Write operations stubbed; story ROM is immutable.
 */
void z_write_byte(uint32_t address, uint8_t value) {
    (void)address; (void)value;
}

void z_write_word(uint32_t address, uint16_t value) {
    (void)address; (void)value;
}

/**
 * Initialize memory (stub for now, no dynamic mapping needed)
 */
void z_init_memory(void) {}
