/**
 * src/z_memory.c
 * -------------------------------------------------------------------------
 * Minimal banked memory access for Zork GB MVP build.
 */

#include <gb/gb.h>
#include <stdint.h>
#include "z_memory.h"
#include "zork_data/zork_data.h"  // Generated by bin2banks.py

 // Read a byte from Zork ROM data (banked)
uint8_t z_read_byte(uint32_t address) {
    uint8_t bank = ZORK_DATA_BANK_START + (address / ZORK_BANK_SIZE);
    uint16_t offset = address % ZORK_BANK_SIZE;

    // Only allow banks that exist
    if (bank < ZORK_DATA_BANK_START || bank >= ZORK_DATA_BANK_START + ZORK_DATA_NUM_BANKS) {
        return 0; // out-of-range safe fallback
    }

    SWITCH_ROM(bank);

    switch (bank) {
#if ZORK_DATA_NUM_BANKS >= 1
    case 1: return zork_bank1_data[offset];
#endif
#if ZORK_DATA_NUM_BANKS >= 2
    case 2: return zork_bank2_data[offset];
#endif
#if ZORK_DATA_NUM_BANKS >= 3
    case 3: return zork_bank3_data[offset];
#endif
#if ZORK_DATA_NUM_BANKS >= 4
    case 4: return zork_bank4_data[offset];
#endif
#if ZORK_DATA_NUM_BANKS >= 5
    case 5: return zork_bank5_data[offset];
#endif
#if ZORK_DATA_NUM_BANKS >= 6
    case 6: return zork_bank6_data[offset];
#endif
    default: return 0;
    }
}

// Read a 16-bit word
uint16_t z_read_word(uint32_t address) {
    return ((uint16_t)z_read_byte(address) << 8) | z_read_byte(address + 1);
}

// Placeholder writes (story ROM is read-only)
void z_write_byte(uint32_t address, uint8_t value) {
    (void)address; (void)value;
}

void z_write_word(uint32_t address, uint16_t value) {
    (void)address; (void)value;
}

// Minimal stub to satisfy main.c
void z_init_memory(void) {}
