#include <stdint.h>
#include "z_memory.h"

 /**
  * External reference to the raw story file binary.
  * This symbol is generated by the Makefile via data/zork_data.s
  */
extern const uint8_t zork_data[];

/**
 * Reads a single byte from the Z-Machine memory map.
 * @param address: 32-bit logical address.
 */
uint8_t z_read_byte(uint32_t address) {
    return zork_data[address];
}

/**
 * Reads a 16-bit word from the Z-Machine memory map (Big Endian).
 * @param address: 32-bit logical address.
 */
uint16_t z_read_word(uint32_t address) {
    return ((uint16_t)zork_data[address] << 8) | zork_data[address + 1];
}

/**
 * Writes a byte to the Z-Machine memory map.
 * Note: Requires zork_data to be mapped to writable RAM (WRAM/SRAM).
 */
void z_write_byte(uint32_t address, uint8_t value) {
    ((uint8_t*)zork_data)[address] = value;
}

/**
 * Writes a 16-bit word to the Z-Machine memory map (Big Endian).
 */
void z_write_word(uint32_t address, uint16_t value) {
    ((uint8_t*)zork_data)[address] = (uint8_t)(value >> 8);
    ((uint8_t*)zork_data)[address + 1] = (uint8_t)(value & 0xFF);
}

/**
 * Initialization stub required by main.c
 */
void z_init_memory(void) {
    /* Currently, story data is accessed directly from ROM banks.
       Dynamic memory allocation or WRAM paging would be initialized here. */
}
